# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wexport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Export_win(object):
    def setupUi(self, Export_win):
        Export_win.setObjectName("Export_win")
        Export_win.setWindowModality(QtCore.Qt.ApplicationModal)
        Export_win.resize(800, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/16x16/applications-engineering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Export_win.setWindowIcon(icon)
        Export_win.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        Export_win.setModal(True)
        self.treeView = QtWidgets.QTreeView(Export_win)
        self.treeView.setGeometry(QtCore.QRect(10, 40, 780, 380))
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName("treeView")
        self.comboBox = QtWidgets.QComboBox(Export_win)
        self.comboBox.setGeometry(QtCore.QRect(179, 430, 501, 27))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Export_win)
        self.label.setGeometry(QtCore.QRect(10, 430, 161, 27))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Export_win)
        self.label_2.setGeometry(QtCore.QRect(10, 460, 161, 27))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Export_win)
        self.lineEdit.setGeometry(QtCore.QRect(181, 460, 471, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(Export_win)
        self.toolButton.setGeometry(QtCore.QRect(653, 460, 27, 27))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Export_win)
        self.toolButton_2.setGeometry(QtCore.QRect(230, 10, 26, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/22x22/expandall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(Export_win)
        self.toolButton_3.setGeometry(QtCore.QRect(260, 10, 26, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/22x22/collapsall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setObjectName("toolButton_3")
        self.label_3 = QtWidgets.QLabel(Export_win)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 210, 26))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Export_win)
        self.pushButton.setGeometry(QtCore.QRect(690, 430, 100, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/16x16/document-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Export_win)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 460, 100, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/16x16/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Export_win)
        self.toolButton_2.clicked.connect(self.treeView.expandAll) # type: ignore
        self.toolButton_3.clicked.connect(self.treeView.collapseAll) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Export_win)

    def retranslateUi(self, Export_win):
        _translate = QtCore.QCoreApplication.translate
        Export_win.setWindowTitle(_translate("Export_win", "Експортні матеріали"))
        self.label.setText(_translate("Export_win", "Формат експортних даних"))
        self.label_2.setText(_translate("Export_win", "Експортний файл"))
        self.toolButton.setText(_translate("Export_win", "..."))
        self.label_3.setText(_translate("Export_win", "Експортні матеріали за розділами"))
        self.pushButton.setText(_translate("Export_win", "Експорт"))
        self.pushButton_2.setText(_translate("Export_win", "Відміна"))
