# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'woborud.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Oborud_win(object):
    def setupUi(self, Oborud_win):
        Oborud_win.setObjectName("Oborud_win")
        Oborud_win.resize(700, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/16x16/applications-engineering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Oborud_win.setWindowIcon(icon)
        Oborud_win.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableOborud = QtWidgets.QTableView(self.tab)
        self.tableOborud.setObjectName("tableOborud")
        self.gridLayout_3.addWidget(self.tableOborud, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableOborud_2 = QtWidgets.QTableView(self.tab_2)
        self.tableOborud_2.setObjectName("tableOborud_2")
        self.gridLayout_2.addWidget(self.tableOborud_2, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableOborud_3 = QtWidgets.QTableView(self.tab_3)
        self.tableOborud_3.setObjectName("tableOborud_3")
        self.gridLayout.addWidget(self.tableOborud_3, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableOborud_4 = QtWidgets.QTableView(self.tab_4)
        self.tableOborud_4.setObjectName("tableOborud_4")
        self.gridLayout_4.addWidget(self.tableOborud_4, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableOborud_5 = QtWidgets.QTableView(self.tab_5)
        self.tableOborud_5.setObjectName("tableOborud_5")
        self.gridLayout_5.addWidget(self.tableOborud_5, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableOborud_6 = QtWidgets.QTableView(self.tab_6)
        self.tableOborud_6.setObjectName("tableOborud_6")
        self.gridLayout_6.addWidget(self.tableOborud_6, 0, 0, 1, 1)
        Oborud_win.addTab(self.tab_6, "")

        self.retranslateUi(Oborud_win)
        Oborud_win.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Oborud_win)

    def retranslateUi(self, Oborud_win):
        _translate = QtCore.QCoreApplication.translate
        Oborud_win.setWindowTitle(_translate("Oborud_win", "Обладнання"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab), _translate("Oborud_win", "Геодезичне"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab_2), _translate("Oborud_win", "Геофізичне"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab_3), _translate("Oborud_win", "Бурове"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab_4), _translate("Oborud_win", "Статичного зондування"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab_5), _translate("Oborud_win", "Динамічного зондування"))
        Oborud_win.setTabText(Oborud_win.indexOf(self.tab_6), _translate("Oborud_win", "Лабораторне"))
