# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wreport_par1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report_par1(object):
    def setupUi(self, Report_par1):
        Report_par1.setObjectName("Report_par1")
        Report_par1.setWindowModality(QtCore.Qt.WindowModal)
        Report_par1.resize(960, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/16x16/applications-engineering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Report_par1.setWindowIcon(icon)
        Report_par1.setModal(True)
        self.treeView = QtWidgets.QTreeView(Report_par1)
        self.treeView.setGeometry(QtCore.QRect(9, 9, 940, 510))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(780, 440))
        self.treeView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView.setSizeIncrement(QtCore.QSize(0, 0))
        self.treeView.setFrameShape(QtWidgets.QFrame.Box)
        self.treeView.setAnimated(True)
        self.treeView.setWordWrap(True)
        self.treeView.setObjectName("treeView")
        self.label = QtWidgets.QLabel(Report_par1)
        self.label.setGeometry(QtCore.QRect(20, 530, 140, 27))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Report_par1)
        self.label_2.setGeometry(QtCore.QRect(280, 530, 140, 27))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Report_par1)
        self.label_3.setGeometry(QtCore.QRect(280, 560, 140, 27))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Report_par1)
        self.lineEdit.setGeometry(QtCore.QRect(170, 530, 100, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Report_par1)
        self.comboBox.setGeometry(QtCore.QRect(430, 530, 250, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Report_par1)
        self.comboBox_2.setGeometry(QtCore.QRect(430, 560, 250, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(Report_par1)
        self.pushButton.setGeometry(QtCore.QRect(709, 530, 220, 27))
        self.pushButton.setBaseSize(QtCore.QSize(100, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/16x16/document-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Report_par1)
        self.pushButton_2.setGeometry(QtCore.QRect(709, 560, 220, 27))
        self.pushButton_2.setBaseSize(QtCore.QSize(100, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/16x16/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Report_par1)
        QtCore.QMetaObject.connectSlotsByName(Report_par1)
        Report_par1.setTabOrder(self.treeView, self.lineEdit)
        Report_par1.setTabOrder(self.lineEdit, self.comboBox)
        Report_par1.setTabOrder(self.comboBox, self.comboBox_2)
        Report_par1.setTabOrder(self.comboBox_2, self.pushButton)
        Report_par1.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, Report_par1):
        _translate = QtCore.QCoreApplication.translate
        Report_par1.setWindowTitle(_translate("Report_par1", "Параметри звіту"))
        self.label.setText(_translate("Report_par1", "Номер документа"))
        self.label_2.setText(_translate("Report_par1", "Документ склав"))
        self.label_3.setText(_translate("Report_par1", "Документ перевірив"))
        self.pushButton.setText(_translate("Report_par1", "Звіт"))
        self.pushButton_2.setText(_translate("Report_par1", "Відміна"))
