# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wreport_par.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report_par(object):
    def setupUi(self, Report_par):
        Report_par.setObjectName("Report_par")
        Report_par.setWindowModality(QtCore.Qt.WindowModal)
        Report_par.resize(460, 174)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/16x16/applications-engineering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Report_par.setWindowIcon(icon)
        Report_par.setModal(True)
        self.label = QtWidgets.QLabel(Report_par)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 27))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Report_par)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 33))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Report_par)
        self.label_3.setGeometry(QtCore.QRect(10, 87, 141, 33))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Report_par)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 112, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Report_par)
        self.comboBox.setGeometry(QtCore.QRect(160, 50, 261, 33))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(Report_par)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 87, 261, 33))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(Report_par)
        self.pushButton.setGeometry(QtCore.QRect(160, 130, 112, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setBaseSize(QtCore.QSize(100, 0))
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/16x16/dialog-ok-apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Report_par)
        QtCore.QMetaObject.connectSlotsByName(Report_par)
        Report_par.setTabOrder(self.lineEdit, self.comboBox)
        Report_par.setTabOrder(self.comboBox, self.comboBox_2)
        Report_par.setTabOrder(self.comboBox_2, self.pushButton)

    def retranslateUi(self, Report_par):
        _translate = QtCore.QCoreApplication.translate
        Report_par.setWindowTitle(_translate("Report_par", "Параметри звіту"))
        self.label.setText(_translate("Report_par", "Номер документа"))
        self.label_2.setText(_translate("Report_par", "Документ склав"))
        self.label_3.setText(_translate("Report_par", "Документ перевірив"))
        self.pushButton.setText(_translate("Report_par", "OK"))
