# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtipbur.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tipbur_win(object):
    def setupUi(self, Tipbur_win):
        Tipbur_win.setObjectName("Tipbur_win")
        Tipbur_win.resize(700, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/16x16/applications-engineering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tipbur_win.setWindowIcon(icon)
        Tipbur_win.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableTipbur = QtWidgets.QTableView(self.tab)
        self.tableTipbur.setObjectName("tableTipbur")
        self.gridLayout_3.addWidget(self.tableTipbur, 0, 0, 1, 1)
        Tipbur_win.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableTipbur_2 = QtWidgets.QTableView(self.tab_2)
        self.tableTipbur_2.setObjectName("tableTipbur_2")
        self.gridLayout_2.addWidget(self.tableTipbur_2, 0, 0, 1, 1)
        Tipbur_win.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableTipbur_3 = QtWidgets.QTableView(self.tab_3)
        self.tableTipbur_3.setObjectName("tableTipbur_3")
        self.gridLayout.addWidget(self.tableTipbur_3, 0, 0, 1, 1)
        Tipbur_win.addTab(self.tab_3, "")

        self.retranslateUi(Tipbur_win)
        Tipbur_win.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Tipbur_win)

    def retranslateUi(self, Tipbur_win):
        _translate = QtCore.QCoreApplication.translate
        Tipbur_win.setWindowTitle(_translate("Tipbur_win", "Бурові установки"))
        Tipbur_win.setTabText(Tipbur_win.indexOf(self.tab), _translate("Tipbur_win", "Самохідні"))
        Tipbur_win.setTabText(Tipbur_win.indexOf(self.tab_2), _translate("Tipbur_win", "Плавучі"))
        Tipbur_win.setTabText(Tipbur_win.indexOf(self.tab_3), _translate("Tipbur_win", "Малогабаритні"))
